### PR TITLE
Feature/fun-apis

### PR DESCRIPTION
**Pull request by deemo-o**
- implemented 4 fun apis

### CODE REVIEW

**Comment by deemo-o** [comment]
For the dictionary command, if the definition exceeds 1024 characters, this error will occur:

`Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body In embeds.0.fields.1.value: Must be 1024 or fewer in length.`

I'm having trouble understanding how to fix the error. Could you guys give me some suggestions?

**Comment by siwuagain** [comment]
> For the dictionary command, if the definition exceeds 1024 characters, this error will occur:
> 
> `Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body In embeds.0.fields.1.value: Must be 1024 or fewer in length.`
> 
> I'm noob so maybe you guys can help me :)

I have some suggestions, but I would also like your input on them:
- We could look for a better dictionary API together (PyDictionary and the Merriam-Webster Dictionary come to mind)
- Use some sort of "if" statement to get only the first definition if the definition surpasses 1024 characters
- Based on the previous point, we could fetch only the first few definitions for each term as a way to standardize things

Great work, everything else looks very good

**Comment by Kenny-star** [comment]
To add on @siwuagain, it would also a good idea to run try/catch statements and we could make an error specifying that the word does not exist in the Dictionary's database. Otherwise, everything looks good to me!

**Review by Kenny-star — CHANGES_REQUESTED** [review]
Will need a try/catch for better error handling, otherwise LGTM!

**Comment by deemo-o** [comment]
Alright, I decided to use the PyDictionary library as @siwuagain suggested and it's been working great. The following is how the embed currently looks like.

image

The word apple only had two definitions, but I also implemented a validation system to check if the character count exceeded 1024 for the values of the Noun, Adjective, and Verb fields.

image

In this screenshot, the value of the Noun field was going to exceed 1024 characters so I made sure that if the next definition was going to exceed the character limit, the program would break out of the for loop that was going to append the next definition. 

Here's the implementation:

```py
if "Noun" in definitions.keys():
    for index, definition in enumerate(definitions["Noun"]):
        nouns_char += len(definition)
        if nouns_char > max_char:
            break
        nouns += f"{index + 1} - {definition.capitalize()}\n"
```

Thank you @Kenny-star and @siwuagain for the suggestions, please review my new implementations.

**Review by Kenny-star — APPROVED** [review]
LGTM! Well Done!

**Comment by siwuagain** [comment]
> Alright, I decided to use the PyDictionary library as @siwuagain suggested and it's been working great. The following is how the embed currently looks like.
> 
> image
> 
> The word apple only had two definitions, but I also implemented a validation system to check if the character count exceeded 1024 for the values of the Noun, Adjective, and Verb fields.
> 
> image
> 
> In this screenshot, the value of the Noun field was going to exceed 1024 characters so I made sure that if the next definition was going to exceed the character limit, the program would break out of the for loop that was going to append the next definition.
> 
> Here's the implementation:
> 
> ```python
> if "Noun" in definitions.keys():
>     for index, definition in enumerate(definitions["Noun"]):
>         nouns_char += len(definition)
>         if nouns_char > max_char:
>             break
>         nouns += f"{index + 1} - {definition.capitalize()}\n"
> ```
> 
> Thank you @Kenny-star and @siwuagain for the suggestions, please review my new implementations.

I did not think about that, it's a great idea. Good work

**Review by siwuagain — APPROVED** [review]

**Pull request merged**
