### PR TITLE
Feature/typeracer-game

### PR DESCRIPTION
**Pull request by deemo-o**
I've finished implementing the first version of the typeracer game and the Glicko-2 rating system.

How the typeracer game works:
- You can play a match by yourself or play another discord user by tagging them.
- You will have 10 seconds to read the rules and information about the match before the paragraph you need to type out appears.
- The paragraph is generated using the NLTK library using the corpus from Brown University. The paragraph is properly formatted using regular expressions ([paragraph_formatter.py](https://github.com/deemo-o/Zen/blob/feature/typeracer-game/utils/games_utils/paragraph_formatter.py)).
- You will have a maximum of 2 minutes to finish typing the paragraph. There will be a timer at the top updating every 5 seconds. If there are only 10 seconds remaining, the timer will update every second until the time runs out.
- Solo play: Once you send your version of the paragraph, the time, the amount of typos and the amount of missed words will be displayed. The final score is the sum of the time, the amount of typos and the amount of missed words. Typos and missed words count as 2 extra seconds. At the end, your version of the paragraph will be displayed. Typos will be highlighted.
- Match play: Same thing as solo play but it will wait until both players have sent their version of the paragraph before displaying the results. Ratings get adjusted based on the game outcome (lowest score wins).
- Copy and pasting the original paragraph is prohibited and will result in a loss with "player is a cheater!" displayed in their version of the paragraph.

How the Glicko-2 rating system works:
- Uses the [Glicko-2 system](https://www.glicko.net/glicko/glicko2.pdf) by Professor Mark E. Glickman.
- Implemented in [glicko2.py](https://github.com/deemo-o/Zen/blob/feature/typeracer-game/utils/games_utils/glicko2.py) with comments.
- The typeracer game currently updates a player's rating based off of 1 game as opposed to a series of games.
- I also implemented a way to track if one of the player has been inactive. Inactivity will increase their rating deviation.

Commands available:
- typeracer: Puts you in the matchmaking queue (unrated and rated) and waits until you find an opponent.
- typeracerduel: Start a typeracer match between the person you and the person you speficied.
- typeracersolo: Improve your typing against yourself.
- typeracertop: Displays the highest rated typeracer players.

Issues/inconveniences:
- ~~Only one typeracer match can take place at a time due to using tasks for the implementation.~~

Ideas/plans:
- Implement a player profile command to display the player's rating, winrate%, matches won, matches lost, matches played, etc.
- Implement a history command to display a player's match history.
- ~~Implement a matchmaking system. Ranked and unranked.~~
- Make it possible to update a player's rating every 10 games instead of every game.
- Etc.

Some screenshots of the typeracer game in action:

**Rules and match information - Solo Play**
image
**Rules and match information - Match Play**
image
**Paragraph and timer information**
image
**Result - Solo Play**
image
**Result - Match Play**
image
**Result - Match Play - Cheater Detected**
image

### CODE REVIEW

**Review by siwuagain — APPROVED** [review]
very thorough feature!

**Comment by deemo-o** [comment]
**Honorable Mention**

Lawrence Liang AKA blind monkey seems to have no idea how the Glicko-2 system works. Do not be like him. Be better.

image

**Review by LawrenceLiang02 — APPROVED** [review]
Great work, it is a fun game! No comment to be added.

**Review by Kenny-star — APPROVED** [review]
Great initiative, and what an amazing job from start to finish! Clever and challenging idea implementing a find match game queue and the glicko-2 system.

**Pull request merged**
