### PR TITLE
Feature/moderation

### PR DESCRIPTION
**Pull request by deemo-o**
Added a bunch of commands that will be useful for staff members and some that will be useful for users.

Here are the commands:

- clearmessage: Allows a staff member to clear an `amount` of message(s) in a channel. If the staff specifies a user, it will look in the last `amount` message(s) and clear all message(s) sent by that user.
- warn: Lets a staff member warn a specific user by sending a customized warning message to the user via the bot's DMs.
- lockchannel: Locks the entire channel preventing users from sending messages in it (Kind of like a global mute).
- unlockchannel: Unlocks the channel that was previously locked.
- adminhelp: Lets a user send a customized message to all admins in the server via the bot's DMs.
- poll: Lets a staff member start a poll with a question and the time limit.

Future ideas/plans:

- To make the `rolesetup` command better, we can implement the SQLite database with the moderation module, allowing staff members to add, modify, delete and get roles from the database.
- A ticketing system to report bugs, users, suggest features, etc.
- Basic commands to manage users: kick, ban, mute, etc.

Here are some screenshots of how the commands look like:

image
image
image
image
image
image
image

### CODE REVIEW

**Review by LawrenceLiang02 — APPROVED** [review]
I see that you have implemented very useful commands, however I do not understand how music.py needs to be modified for moderation commands. Please shed some light on this matter. 

Everything else looks perfect, great job!
Edit: Explained and understood! No further comment!

**Comment by deemo-o** [comment]
> I see that you have implemented very useful commands, however I do not understand how music.py needs to be modified for moderation commands. Please shed some light on this matter.
> 
> Everything else looks perfect, great job! Edit: I see that you have a music embed error commit but still, how does this affect moderation?

It doesn't affect the moderation module at all. Just a quality of life change that has nothing to do with the moderation module. The same thing was done for commit [2fa4cf2](https://github.com/deemo-o/Zen/pull/14/commits/2fa4cf2215df8828f43792eac8f9969139f545e3) and [5fed30a](https://github.com/deemo-o/Zen/pull/14/commits/5fed30aa833408fd4934008fcba0afdabee54e52).

**Comment by LawrenceLiang02** [comment]
> > I see that you have implemented very useful commands, however I do not understand how music.py needs to be modified for moderation commands. Please shed some light on this matter.
> > Everything else looks perfect, great job! Edit: I see that you have a music embed error commit but still, how does this affect moderation?
> 
> It doesn't affect the moderation module at all. Just a quality of life change that has nothing to do with the moderation module. The same thing was done for commit [2fa4cf2](https://github.com/deemo-o/Zen/pull/14/commits/2fa4cf2215df8828f43792eac8f9969139f545e3) and [5fed30a](https://github.com/deemo-o/Zen/pull/14/commits/5fed30aa833408fd4934008fcba0afdabee54e52).

So what you are saying is that you are too lazy to open a bug PR to fix the si

**Comment by LawrenceLiang02** [comment]
> > I see that you have implemented very useful commands, however I do not understand how music.py needs to be modified for moderation commands. Please shed some light on this matter.
> > Everything else looks perfect, great job! Edit: I see that you have a music embed error commit but still, how does this affect moderation?
> 
> It doesn't affect the moderation module at all. Just a quality of life change that has nothing to do with the moderation module. The same thing was done for commit [2fa4cf2](https://github.com/deemo-o/Zen/pull/14/commits/2fa4cf2215df8828f43792eac8f9969139f545e3) and [5fed30a](https://github.com/deemo-o/Zen/pull/14/commits/5fed30aa833408fd4934008fcba0afdabee54e52).

I see, thanks for the reply!

**Comment by deemo-o** [comment]
> > > I see that you have implemented very useful commands, however I do not understand how music.py needs to be modified for moderation commands. Please shed some light on this matter.
> > > Everything else looks perfect, great job! Edit: I see that you have a music embed error commit but still, how does this affect moderation?
> > 
> > 
> > It doesn't affect the moderation module at all. Just a quality of life change that has nothing to do with the moderation module. The same thing was done for commit [2fa4cf2](https://github.com/deemo-o/Zen/pull/14/commits/2fa4cf2215df8828f43792eac8f9969139f545e3) and [5fed30a](https://github.com/deemo-o/Zen/pull/14/commits/5fed30aa833408fd4934008fcba0afdabee54e52).
> 
> So what you are saying is that you are too lazy to open a bug PR to fix the embeds

You're right. Next time I'll make sure to open 3 other pull requests excluding this one to fix the bugs. Actually they aren't bugs, but quality of life additions.

**Comment by LawrenceLiang02** [comment]
> > > > I see that you have implemented very useful commands, however I do not understand how music.py needs to be modified for moderation commands. Please shed some light on this matter.
> > > > Everything else looks perfect, great job! Edit: I see that you have a music embed error commit but still, how does this affect moderation?
> > > 
> > > 
> > > It doesn't affect the moderation module at all. Just a quality of life change that has nothing to do with the moderation module. The same thing was done for commit [2fa4cf2](https://github.com/deemo-o/Zen/pull/14/commits/2fa4cf2215df8828f43792eac8f9969139f545e3) and [5fed30a](https://github.com/deemo-o/Zen/pull/14/commits/5fed30aa833408fd4934008fcba0afdabee54e52).
> > 
> > 
> > So what you are saying is that you are too lazy to open a bug PR to fix the embeds
> 
> You're right. Next time I'll make sure to open 3 other pull requests excluding this one to fix the bugs. Actually they aren't bugs, but quality of life additions.

Then that should be a new feature! Thanks for the hasty reply!

**Comment by deemo-o** [comment]
> 



> > > > > I see that you have implemented very useful commands, however I do not understand how music.py needs to be modified for moderation commands. Please shed some light on this matter.
> > > > > Everything else looks perfect, great job! Edit: I see that you have a music embed error commit but still, how does this affect moderation?
> > > > 
> > > > 
> > > > It doesn't affect the moderation module at all. Just a quality of life change that has nothing to do with the moderation module. The same thing was done for commit [2fa4cf2](https://github.com/deemo-o/Zen/pull/14/commits/2fa4cf2215df8828f43792eac8f9969139f545e3) and [5fed30a](https://github.com/deemo-o/Zen/pull/14/commits/5fed30aa833408fd4934008fcba0afdabee54e52).
> > > 
> > > 
> > > So what you are saying is that you are too lazy to open a bug PR to fix the embeds
> > 
> > 
> > You're right. Next time I'll make sure to open 3 other pull requests excluding this one to fix the bugs. Actually they aren't bugs, but quality of life additions.
> 
> Then that should be a new feature! Thanks for the hasty reply!

Handling error technically isn't a feature, but I do get what you mean. Don't worry about it!

**Comment by siwuagain** [comment]
> Added a bunch of commands that will be useful for staff members and some that will be useful for users.
> 
> Here are the commands:
> 
> * clearmessage: Allows a staff member to clear an `amount` of message(s) in a channel. If the staff specifies a user, it will look in the last `amount` message(s) and clear all message(s) sent by that user.
> * warn: Lets a staff member warn a specific user by sending a customized warning message to the user via the bot's DMs.
> * lockchannel: Locks the entire channel preventing users from sending messages in it (Kind of like a global mute).
> * unlockchannel: Unlocks the channel that was previously locked.
> * adminhelp: Lets a user send a customized message to all admins in the server via the bot's DMs.
> * poll: Lets a staff member start a poll with a question and the time limit.
> 
> Future ideas/plans:
> 
> * To make the `rolesetup` command better, we can implement the SQLite database with the moderation module, allowing staff members to add, modify, delete and get roles from the database.
> * A ticketing system to report bugs, users, suggest features, etc.
> * Basic commands to manage users: kick, ban, mute, etc.
> 
> Here are some screenshots of how the commands look like:
> 
> image
> 
> image
> 
> image
> 
> image
> 
> image
> 
> image
> 
> image
> 
> image

i'd like to report an abuse of power from debo xijinping huang  
image

**Review by siwuagain — APPROVED** [review]
Good work, very useful features for moderating

**Pull request merged**
